HANDOFF_PHRASES: list[str] = [
    "hablar con asesor",
    "hablar con humano",
    "hablar con persona",
    "hablar con alguien",
    "hablar con un asesor",
    "hablar con un humano",
    "hablar con una persona",
    "atencion humana",
    "atención humana",
    "atender persona",
    "necesito asesor",
    "necesito un asesor",
    "necesito humano",
    "necesito un humano",
    "necesito hablar con",
    "quiero asesor",
    "quiero un asesor",
    "quiero hablar con asesor",
    "quiero hablar con humano",
    "quiero hablar con un asesor",
    "contactar asesor",
    "contactar con asesor",
    "contactar un asesor",
    "contacto con asesor",
    "comunicar asesor",
    "comunicarme con asesor",
    "comunicarme con un asesor",
    "presentar reclamo",
    "presentar queja",
    "hacer reclamo",
    "hacer un reclamo",
    "tengo un reclamo",
    "tengo una queja",
    "poner queja",
    "poner reclamo",
]

HANDOFF_SOFT_KEYWORDS: list[str] = [
    "asesor",
    "ejecutivo",
    "agente humano",
]

HANDOFF_KEYWORDS: list[str] = HANDOFF_PHRASES + HANDOFF_SOFT_KEYWORDS
